### ISSUE TITLE
KeyError: 'weight'

### ISSUE THREAD

**Issue by scau-cc** [chirag126/nifty#1]
When I run script 2, I got the error as  follow. I don't why. I never adjust the code before i run and the environment is same as your.

Using backend: pytorch
Traceback (most recent call last):
  File "nifty_sota_gnn.py", line 211, in <module>
    encoder = Encoder(in_channels=features.shape[1], out_channels=args.hidden, base_model=args.encoder).to(device)
  File "/home/yczhu/gnn/nifty/models/ssf.py", line 155, in __init__
    self.conv = GCN(in_channels, out_channels)
  File "/home/yczhu/gnn/nifty/models/ssf.py", line 29, in __init__
    self.gc1 = spectral_norm(GCNConv(nfeat, nhid))
  File "/home/yczhu/anaconda3/envs/nifty/lib/python3.7/site-packages/torch/nn/utils/spectral_norm.py", line 254, in spectral_norm
    SpectralNorm.apply(module, name, n_power_iterations, dim, eps)
  File "/home/yczhu/anaconda3/envs/nifty/lib/python3.7/site-packages/torch/nn/utils/spectral_norm.py", line 116, in apply
    weight = module._parameters[name]
KeyError: 'weight'

Can you tell me what happen about that?

**Comment by Fecsio** [comment]
Hi.
I had the same problem and the solution was to install a specific version of torch-geometric, since in newer versions the implementation of some modules is completely different. 
If I remember correctly, it should work with torch-geometric <= 1.7. 
Hope this helps

**Comment by scau-cc** [comment]
您好 我是朱裕昌 我已收到你的来信 谢谢啦~ 与食俱进 食力无限

**Comment by scau-cc** [comment]
@Fecsio Thank you for your help!

**Comment by scau-cc** [comment]
您好 我是朱裕昌 我已收到你的来信 谢谢啦~ 与食俱进 食力无限
